### ISSUE TITLE
About releasing Dataset and the processing code

### ISSUE THREAD

**Issue by yunfan1202** [artonson/def#11]
Hello, great work!
Do you have any schedule for releasing the Synthetic Datasets "DEF-Sim" and its corresponding processing code for the ABC dataset?

**Comment by artonson** [comment]
Hi! We're planning on having the data and models public within probably an upcoming month. We would really like to have it easy to use and robustly working.

**Comment by yunfan1202** [comment]
By the way, how to use the code to extract parametric curve with the input of point cloud edges (and the distance-to-feature field)? 

Another question to discuss the parametric curve performance:
If one do not have the distance-to-feature field and have the locations of point cloud edges, is it still possible to decide the "sharp" points and corners to get similar performance?

Thank you so much for your time!!

**Comment by artonson** [comment]
Dear Yunfan,

We finally release the entire codebase for our SIGGRAPH’22 paper DEF: Deep Estimation of Sharp Geometric Features in 3D Shapes. This took several months of intermittent cleaning/refactoring and the code is now available at https://github.com/artonson/def 

We release 14 large-scale training and evaluation datasets, including 2 datasets with real-world scanned data, 37 separate pre-trained networks, and predictions results for our method for feature estimation and vectorisation, totalling over 200 Gb of various data. 

Let me know is anything is wrong so I could actually improve the code.

With regards,
Alexey
