### ISSUE TITLE
Link error in "Generating synthetic training datasets" section

### ISSUE THREAD

**Issue by Valengag** [artonson/def#12]
The link about [synthetic_data/complete_models/] in "Generating synthetic training datasets" section is redirecting on the patch Dropbox and not the complete models.

**Comment by artonson** [comment]
Hello Valengag,

Thank you for noticing the issue. We've now updated the link to lead to the actual complete 3D model datasets, and we provide the link also here: [synthetic complete 3d models](https://www.dropbox.com/scl/fo/yizmgvuxtdblqqr6656c1/h?dl=0&rlkey=10knittkmv6v64dsmhdsbytx8).
